[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_port = 8069
list_db = True
proxy_mode = False
without_demo = all
data_dir = /var/lib/odoo
# Override di entrypoint via --addons-path (community + enterprise).
addons_path = /opt/odoo/enterprise,/opt/odoo/community/addons,/opt/odoo/community/odoo/addons,/mnt/extra-addons
logfile = /var/lib/odoo/odoo.log
